### ISSUE TITLE
Crash during shader load.

### ISSUE THREAD

**Issue by Elabajaba** [Angelo1211/HybridRenderingEngine#30] opened 2018-12-28 05:13 UTC
Attempted to launch the hybridRenderer.exe, the console window shows Loading Complete!..., but the Hybrid Rendering Engine window is unresponsive and stays blank white while using ~18% CPU, 0% GPU and ~124MB memory.

Windows 10, i7 5930k, 32GB RAM, 1080ti with 416.94 driver using the v0.1 release.

Full text from console is
Vendor:   NVIDIA Corporation
Renderer: GeForce GTX 1080 Ti/PCIe/SSE2
Version:  4.6.0 NVIDIA 416.94

Beginning Scene load, checking scene description file:
../assets/scenes/Sponza.json is a valid file
Loading camera...
Loading models...
../assets/models/Sponza/Sponza.gltf is a valid file
Loading skybox...
Loading lights...
Loading directional light...
Loading point light...
Generating environment maps...
Reticulating splines...
Loading Complete!...

**Comment by Angelo1211** [comment] 2018-12-28 11:30
Hi! Thanks for letting me know of the bug and sharing your error log! I took a look at it and it seems like all the scene data is loading fine, but the issues are located at the renderManager initialization time. To pinpoint the exact location  I've added some more print statements to the loading process and pushed those to the source. 

There's three things I've thought of so far that we can do to fix this:

1. Download [newBin.zip](https://github.com/Angelo1211/HybridRenderingEngine/files/2714744/newBin.zip) and replace the contents of the bin folder with the.zip file. This is the compiled version of the small changes I made that add more print statements to the program. If you could re-run and copy the console text in here again that would help me pinpoint further where the issue is. 

2. I've also made the bin a debug version with a pdb file so, If you have visual studio (or some other debugger) you should be able to debug the HybridRenderer.exe file and see in which line it's actually getting stuck on. 

3. If for whatever whatever reason none of the above works either, we'll have to move on to compiling from source and trying to debug that instead. But hopefully this isn't necessary.

Let me know how it goes!

**Comment by Elabajaba** [comment] 2018-12-28 23:37
It gets stuck Loading Shaders. Running it with the visual studio debugger shows 

> 'hybridRenderer.exe' (Win32): Loaded 'D:\Downloads\HRE v0.1 Aachen\bin\hybridRenderer.exe'. Symbols loaded.
...
Exception thrown at 0x00007FFC5DFDA388 in hybridRenderer.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x0000002A60B0E198.
The thread 0x374c has exited with code 0 (0x0).
The thread 0x213c has exited with code 0 (0x0).
The thread 0x1bc4 has exited with code 0 (0x0).

Vendor:   NVIDIA Corporation
Renderer: GeForce GTX 1080 Ti/PCIe/SSE2
Version:  4.6.0 NVIDIA 416.94

Beginning Scene load, checking scene description file:
../assets/scenes/Sponza.json is a valid file
Loading camera...
Loading models...
../assets/models/Sponza/Sponza.gltf is a valid file
Loading skybox...
Loading lights...
Loading directional light...
Loading point light...
Generating environment maps...
Reticulating splines...
Loading Complete!...

Initializing Renderer.
Loading FBO's...
Loading Shaders...

Cloned and ran the repo in vs, "Exception thrown at 0x00007FFC5DFDA388 in hybridRenderer.exe: Microsoft C++ exception: DeadlyImportError at memory location 0x0000008B18B7DDF8." seems to happen in model.cpp line 18 "const aiScene *scene = importer.ReadFile(path, aiProcess_Triangulate | aiProcess_OptimizeMeshes |aiProcess_CalcTangentSpace | aiProcess_FlipUVs);" when loading Sponza, but doesn't cause the program to hang.

Stepping through the shaders it gets to clusterCullLightShader.comp in shader.cpp line 191 "glGetProgramiv(ID, GL_LINK_STATUS, &success);" and then it starts to hang. This is also where the "The thread 0x... has exited with code 0 (0x0). starts, as well as the cpu usage spikes from 9% to 17% and memory usage doubles from ~600MB to 1.2GB in debug build.

**Comment by Elabajaba** [comment] 2018-12-29 05:13
HREUtils::printComputeSizes(); output:
> max global (total) work group size x:2147483647 y:65535 z:65535
max local (in one shader) work group sizes x:1536 y:1024 z:64

![image](https://user-images.githubusercontent.com/177631/50533737-6d307380-0b28-11e9-9d91-be48ba60bfc0.png)

**Comment by SirKnightTG** [comment] 2019-02-16 05:20
This is a driver bug.

NVIDIA is looking into it.

**Comment by Angelo1211** [comment] 2019-02-21 19:00
@SirKnightTG If that's the case I'll close the issue for now.

**Closed by Angelo1211** 2019-02-21 19:00 UTC
Labels: bug

**Comment by shakesoda** [comment] 2019-08-16 17:28
i know this issue is marked closed, but i ran into it and put some time into finding a workaround anyway.

this is the source of the lockup: https://github.com/Angelo1211/HybridRenderingEngine/blob/master/assets/shaders/ComputeShaders/clusterCullLightShader.comp#L115-L120

changing to this worked for me, since it seems nvidia's glsl compiler doesn't like indexing into vecs dynamically with array syntax.

```glsl
float checkAxis(float tmin, float tmax, float v) {
    if (v < tmin) {
        return (tmin - v) * (tmin - v);
    }
    if (v > tmax) {
        return (v - tmax) * (v - tmax);
    }
    return 0.0;
}

float sqDistPointAABB(vec3 point, uint tile){
    float sqDist = 0.0;
    VolumeTileAABB currentCell = cluster[tile];
    cluster[tile].maxPoint[3] = tile;
    sqDist += checkAxis(currentCell.minPoint.x, currentCell.maxPoint.x, point.x);
    sqDist += checkAxis(currentCell.minPoint.y, currentCell.maxPoint.y, point.y);
    sqDist += checkAxis(currentCell.minPoint.z, currentCell.maxPoint.z, point.z);
    return sqDist;
}
```

...then, with that sorted out, https://github.com/Angelo1211/HybridRenderingEngine/blob/master/assets/shaders/PBRClusteredShader.frag#L213 needs to be changed to `FragColor = vec4(colors[uint(mod(zTile, 8))], 1.0);` to compile.
